Csv export 333
asulibraries/islandora-repo pull request #362
Opened 2021-04-01 15:52 UTC by wgilling

This feels pretty big and the likelihood that it needs more work on some fields is pretty high in my estimation, but it's time to get the merge process started with a review.

First note is that all multi-field delimiters have been changed from the "||" to " || " so that items with missing parts such as no subtitle on a complex title paragraph may be imported without confusion. The migrate_plus.migration.csv.yml has this delimiter coded into those fields, so I only mention this because the previous migrations from legacy CSV had the delimiters with no spaces around them.

The view `rest_csv_export` provides three different displays -- one for single item, collection, and search. These all have endpoints that make it fairly easy to manually download any given CSV export. For example, and item that is at `items/12345` has the route `items/12345/csv` and a collection that has `collections/123` has the csv route at `collections/123/csv` and any search pattern should be supported by adding the /csv to the end such as `search/csv?search_api_fulltext=data`. There should be a link in the Admin Toolbox to Download CSV from the items and collections page and another link on search pages near the "Export MODS XML".

The code uses Migrate Source UI in order to allow for a web interface for importing any CSV that was exported and modified. This is at http://localhost:8000/migrate_source_ui and is "Import/Update nodes from CSV (supports csv)".

To test, it seems that you know what to do... but it can be a fairly long process to set up alternate field vocabulary for testing purposes. When exporting, I found that it saves a lot of time to use a collection that has less than 5 items... not that the export takes a long time to run, but it is much easier to inspect and edit a smaller CSV file.

For a command-line import test, the CSV file that is stored at web/modules/custom/asu_migrate/data/csv.csv can be overwritten in order to just use the `drush migrate:import csv --update` command.

Any questions, please ask.

2021-04-06 22:56 UTC, elizoller commented on web/modules/custom/asu_migrate/src/Plugin/Field/FieldFormatter/VisibilityCSVFormatter.php
> +      $item_entity = @\Drupal::entityTypeManager()->getStorage('node')->load($item_entity_id);
dependency injection?

2021-04-06 22:57 UTC, elizoller commented on web/modules/custom/asu_admin_toolbox/src/Plugin/Block/AdminToolboxBlock.php
> +    $user = User::load(\Drupal::currentUser()->id());
dependency injection?

2021-04-06 22:58 UTC, elizoller commented on web/modules/custom/asu_migrate/config/install/migrate_plus.migration.c270_node.yml
> +# Uninstall this config when the feature is uninstalled
can we take this file out of this PR?

2021-04-13 01:22 UTC, wgilling commented
Addressed the dependency injection issues and removed the c270 file. There were four process plugins that actually needed entityTypeManager to use dependency injection. There was also one bit in the AdminToolboxBlock code that needed dependency injection to replace the User:: call.

Please let me know if there are any issues when reviewing.

2021-04-13 01:22 UTC, wgilling commented
Re-ready to re-review.

2021-04-13 22:14 UTC, elizoller requested changes
I tested the export on several levels (search, collection, item) and after the minor tweaks i pushed up, it seems ok for the collections i have in my local. 

i haven't tested the import back in feature, but did see one thing that'll need addressing which i flagged (the missing date created field)

2021-04-13 22:14 UTC, elizoller commented on web/modules/custom/asu_migrate/config/install/migrate_plus.migration.csv.yml
> +# wgg - Date Created should not be the EDTF field.
why is this commented out?

2021-04-13 22:14 UTC, elizoller commented on web/modules/custom/asu_migrate/src/Plugin/Field/FieldFormatter/VisibilityCSVFormatter.php
> +    $asu_utils = \Drupal::service('asu_utils');
:D dependency injection?

2021-05-05 00:55 UTC, wgilling commented
The latest commit was tested to export and import Created Date and correctly update the node value for that EDTF field.

2021-05-05 02:23 UTC, elizoller approved these changes

2021-05-05 02:23 UTC, merged